//
// Created by zdavid on 02/10/18.
//

#ifndef BLOOD_DONATION_SYSTEM_FILEREADER_H
#define BLOOD_DONATION_SYSTEM_FILEREADER_H

_Bool file_reader(char *FILENAME);

#endif //BLOOD_DONATION_SYSTEM_FILEREADER_H
